### ISSUE TITLE
Multiple-input filter not getting correct data?

### ISSUE THREAD

**Issue by goodgerster** [0xC0000054/gmic-8bf#10] opened 2021-03-24 17:21 UTC
Hello,

I'm using gmic-8bf 2.9.6.3 with Photoshop 22.3.0 and gmic-gimp 2.9.6 with GIMP 2.10.22, both on Windows 10, all amd64 builds. I'm trying to use the ‘Colorize Lineart [Smart Coloring]’ G'MIC filter in ‘Extrapolate Color Spots on Transparent Top Layer’ mode. Called from GIMP, the filter works as expected, but from Photoshop, it does not.

I've prepared a test image to demonstrate, with separate [lineart](https://user-images.githubusercontent.com/9383058/112352578-2c097880-8ccb-11eb-85e8-acf269258ff6.png) and [spots](https://user-images.githubusercontent.com/9383058/112352576-2b70e200-8ccb-11eb-8576-48da17f8e369.png). I've also taken [screenshots of GIMP](https://user-images.githubusercontent.com/9383058/112352582-2ca20f00-8ccb-11eb-8ef9-4b607ec0511a.png) and [of Photoshop](https://user-images.githubusercontent.com/9383058/112352585-2ca20f00-8ccb-11eb-9825-c6a7c2c71a55.png) to show exactly how they are set up before I invoke the respective plugins. The result I get from GIMP, and then 8bf, plugins:

<img width="1920" alt="Screenshot 2021-03-24 175350" src="https://user-images.githubusercontent.com/9383058/112352588-2d3aa580-8ccb-11eb-82a7-981f2d04ac0b.png">
<img width="1920" alt="Screenshot 2021-03-24 175404" src="https://user-images.githubusercontent.com/9383058/112352590-2d3aa580-8ccb-11eb-9257-8e769aa75981.png">

From what I can see, it seems that the filter is merging the colour spots into the lineart layer, reducing the result to black & white, then running itself on that without any colour information. If I use the Paint Bucket tool to crudely expand the colour spots, then I get this:
<img width="526" alt="Screenshot 2021-03-24 181905" src="https://user-images.githubusercontent.com/9383058/112355094-a0451b80-8ccd-11eb-9665-88c802f2ca21.png">

I hope this helps. Thanks for your efforts.

**Comment by 0xC0000054** [comment] 2021-03-24 23:20
I am not sure what the problem is, it looks like it may be something with that specific effect.
When I run `Colorize Lineart [Propagation]` it shows the that the layer data is being received correctly from Photoshop.

**Comment by 0xC0000054** [comment] 2021-04-09 09:10
It turns out that the 8bf plugin was sending layers to G'MIC-Qt in the opposite order that the GIMP plug-in uses.
This was fixed in version 2.9.7.0.

Note that the `Colorize Lineart [Propagation]` filter outputs multiple images, so you will need to load the final image back into Photoshop.

**Closed by 0xC0000054** 2021-04-09 09:10 UTC
